### ISSUE TITLE
some questions?

### ISSUE THREAD

**Issue by lulcat** [AlexanderZhirov/readconf#1]
Hi. It seems like this does not support linebreakup continuation with \\

so it just ignores the rest of \
this line unlike pretty much everything else.

One might not wish to allow this in compatible config files but dunno. It breaks with every tradition out there.
Thoughts? 

Also, it could/would? be nice if it recognises shell like syntax, again multiline, e.g. a *sh array:

arr=("hi" 'there' I live
  "in" 'different'
lines)

your config doesn't handle this well.

e.g. a bash/zsh config file with # as comments and using '\' for mmulti lines 
or arrays over sevceral lines and so on, all will be correctly 'parsed' by say

grep -vE '^[[:space:]]*#|^$'

for php ini or stuff using ; I suppose # can be replaced with that and so on.

yous fails to read them and so I feel it's hmm, a lot of yi haa but missing fundamental./practical compatibility.

Of course, one can define a 'custom' config style which suits it I guess but just throwing this out there. 

one liner process.spawn grep ...

**Comment by alexanderzhirov** [comment]
@lulcat Hi! When writing, I did not include recognition of multiline parameters. Just reading the configuration with one-line parameters.

But it's an interesting idea)

**Comment by lulcat** [comment]
:) good stuff. I will keep an eye on it. Cheers.
